services:
  - type: web
    name: uniuyo-library-system
    plan: free
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /metrics
    envVars:
      - key: NODE_ENV
        value: production
