services:
  - type: web
    name: uniuyo-library-system
    plan: free
    buildCommand: composer install && php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    runtime: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /metrics
    envVars:
      - key: NODE_ENV
        value: production
